spring.application.name=crud-testes

#Configuracao do Neon -> banco postgresql online
spring.datasource.url=jdbc:postgresql://ep-steep-resonance-ac99fd31-pooler.sa-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_HbW2uzQ7deXp&sslmode=require&channelBinding=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPING_DATABASE_USERNAME:postgres}
spring.datasource.password=${SPING_DATABASE_PASSWORD:postgres}



#spring.h2.console.enabled=true
#spring.jpa.show-sql=true

#spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update
